version: '3.7'
services:
  iris:
    container_name: iris_container
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 51773
      - 52773
      - 53773