on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Permissions update
        run: chmod +x `pwd`/.ci/tests_entrypoint.sh 
      - name: Build the docker image
        run: |
          docker build -t iris-image:${GITHUB_SHA} .
      - name: Run the image and execute tests
        run: |
          docker run --rm -i \
            -w /opt/irisapp \
            -v `pwd`/tests:/opt/irisapp/tests \
            -v `pwd`/.ci/tests_entrypoint.sh:/tests_entrypoint.sh \
            --entrypoint /tests_entrypoint.sh \
            iris-image:${GITHUB_SHA}