on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the docker image
        run: |
          docker build -t iris-image:${GITHUB_SHA} .
      - name: Run the image
        run: |
          docker run --rm -i \
            -w /opt/irisapp \
            -v `pwd`/tests:/opt/irisapp/tests \
            --entrypoint /opt/irisapp/tests_entrypoint.sh \
            iris-image:${GITHUB_SHA}