on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose up -d -f ../../docker-compose.yml
      #- name: Test action step
      #  uses: ./.github/actions/test-action
      #  id: hello