on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose up -d; sleep 5; docker exec iris /usr/irissys/dev/Cloud/ICM/waitISC.sh; docker stats --no-stream
      - name: Check environment
        run: sleep 5; docker exec iris /usr/irissys/dev/Cloud/ICM/waitISC.sh; docker stats --no-stream
      #- name: Run tests (step 1) - start IRIS 
      #  run: docker exec iris iris start IRIS
      - name: Run tests (step 2) - run tests
        run: docker exec -t iris iris start IRIS && iris session IRIS < test.script
      - name: Check environment
        run: docker stats --no-stream
      #- name: Run tests (step 2) - open iris session and run tests
      #  run: iris session IRIS < test.script
      #- name: Test action step
      #  uses: ./.github/actions/test-action
      #  id: hello